// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb.proto

package api

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EmptyStruct 空的message，对应真实service只返回error，没有具体返回值
type EmptyStruct struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyStruct) Reset()         { *m = EmptyStruct{} }
func (m *EmptyStruct) String() string { return proto.CompactTextString(m) }
func (*EmptyStruct) ProtoMessage()    {}
func (*EmptyStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}
func (m *EmptyStruct) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EmptyStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EmptyStruct.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EmptyStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyStruct.Merge(m, src)
}
func (m *EmptyStruct) XXX_Size() int {
	return m.Size()
}
func (m *EmptyStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyStruct.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyStruct proto.InternalMessageInfo

type AccountFeedResp struct {
	Items                []*AccountFeedInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AccountFeedResp) Reset()         { *m = AccountFeedResp{} }
func (m *AccountFeedResp) String() string { return proto.CompactTextString(m) }
func (*AccountFeedResp) ProtoMessage()    {}
func (*AccountFeedResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1}
}
func (m *AccountFeedResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountFeedResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountFeedResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountFeedResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountFeedResp.Merge(m, src)
}
func (m *AccountFeedResp) XXX_Size() int {
	return m.Size()
}
func (m *AccountFeedResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountFeedResp.DiscardUnknown(m)
}

var xxx_messageInfo_AccountFeedResp proto.InternalMessageInfo

func (m *AccountFeedResp) GetItems() []*AccountFeedInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

type AccountFeedInfo struct {
	ID         int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"id"`
	TopicID    int64  `protobuf:"varint,2,opt,name=TopicID,proto3" json:"topic_id"`
	ActionType string `protobuf:"bytes,3,opt,name=ActionType,proto3" json:"action_type"`
	ActionTime int64  `protobuf:"varint,4,opt,name=ActionTime,proto3" json:"action_time"`
	ActionText string `protobuf:"bytes,5,opt,name=ActionText,proto3" json:"action_text"`
	ActorID    int64  `protobuf:"varint,6,opt,name=ActorID,proto3" json:"actor_id"`
	ActorType  string `protobuf:"bytes,7,opt,name=ActorType,proto3" json:"actor_type"`
	TargetID   int64  `protobuf:"varint,8,opt,name=TargetID,proto3" json:"target_id"`
	TargetType string `protobuf:"bytes,9,opt,name=TargetType,proto3" json:"target_type"`
	// unix timestamp
	CreatedAt int64 `protobuf:"varint,10,opt,name=CreatedAt,proto3" json:"created_at"`
	// unix timestamp
	UpdatedAt            int64    `protobuf:"varint,11,opt,name=UpdatedAt,proto3" json:"updated_at"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountFeedInfo) Reset()         { *m = AccountFeedInfo{} }
func (m *AccountFeedInfo) String() string { return proto.CompactTextString(m) }
func (*AccountFeedInfo) ProtoMessage()    {}
func (*AccountFeedInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{2}
}
func (m *AccountFeedInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountFeedInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountFeedInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountFeedInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountFeedInfo.Merge(m, src)
}
func (m *AccountFeedInfo) XXX_Size() int {
	return m.Size()
}
func (m *AccountFeedInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountFeedInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountFeedInfo proto.InternalMessageInfo

func (m *AccountFeedInfo) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *AccountFeedInfo) GetTopicID() int64 {
	if m != nil {
		return m.TopicID
	}
	return 0
}

func (m *AccountFeedInfo) GetActionType() string {
	if m != nil {
		return m.ActionType
	}
	return ""
}

func (m *AccountFeedInfo) GetActionTime() int64 {
	if m != nil {
		return m.ActionTime
	}
	return 0
}

func (m *AccountFeedInfo) GetActionText() string {
	if m != nil {
		return m.ActionText
	}
	return ""
}

func (m *AccountFeedInfo) GetActorID() int64 {
	if m != nil {
		return m.ActorID
	}
	return 0
}

func (m *AccountFeedInfo) GetActorType() string {
	if m != nil {
		return m.ActorType
	}
	return ""
}

func (m *AccountFeedInfo) GetTargetID() int64 {
	if m != nil {
		return m.TargetID
	}
	return 0
}

func (m *AccountFeedInfo) GetTargetType() string {
	if m != nil {
		return m.TargetType
	}
	return ""
}

func (m *AccountFeedInfo) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *AccountFeedInfo) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type AccountFeedReq struct {
	TopicID              int64    `protobuf:"varint,1,opt,name=TopicID,proto3" json:"topic_id"`
	Limit                int32    `protobuf:"varint,2,opt,name=Limit,proto3" json:"limit"`
	Offset               int32    `protobuf:"varint,3,opt,name=Offset,proto3" json:"offset"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountFeedReq) Reset()         { *m = AccountFeedReq{} }
func (m *AccountFeedReq) String() string { return proto.CompactTextString(m) }
func (*AccountFeedReq) ProtoMessage()    {}
func (*AccountFeedReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{3}
}
func (m *AccountFeedReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountFeedReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountFeedReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountFeedReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountFeedReq.Merge(m, src)
}
func (m *AccountFeedReq) XXX_Size() int {
	return m.Size()
}
func (m *AccountFeedReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountFeedReq.DiscardUnknown(m)
}

var xxx_messageInfo_AccountFeedReq proto.InternalMessageInfo

func (m *AccountFeedReq) GetTopicID() int64 {
	if m != nil {
		return m.TopicID
	}
	return 0
}

func (m *AccountFeedReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *AccountFeedReq) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func init() {
	proto.RegisterType((*EmptyStruct)(nil), "service.accountfeed.EmptyStruct")
	proto.RegisterType((*AccountFeedResp)(nil), "service.accountfeed.AccountFeedResp")
	proto.RegisterType((*AccountFeedInfo)(nil), "service.accountfeed.AccountFeedInfo")
	proto.RegisterType((*AccountFeedReq)(nil), "service.accountfeed.AccountFeedReq")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_f80abaa17e25ccc8) }

var fileDescriptor_f80abaa17e25ccc8 = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x86, 0x49, 0x6b, 0xbb, 0xed, 0xd4, 0xdd, 0xc5, 0x59, 0x90, 0xb0, 0x17, 0x4d, 0xa9, 0x8b,
	0x54, 0xd0, 0x16, 0xd6, 0x27, 0x68, 0xcd, 0x2a, 0x01, 0x41, 0x19, 0x2b, 0x88, 0x37, 0x35, 0x4d,
	0x4e, 0xe2, 0x80, 0xe9, 0xcc, 0x26, 0x27, 0xb2, 0xbd, 0xf0, 0xfd, 0xbc, 0xf4, 0x09, 0x82, 0xf4,
	0x32, 0x97, 0x3e, 0x81, 0xe4, 0x4c, 0xdd, 0xa4, 0x28, 0xee, 0x55, 0x67, 0xfe, 0xf3, 0x9d, 0x7f,
	0x7e, 0x7a, 0x4e, 0x58, 0x4f, 0xaf, 0xa7, 0x3a, 0x55, 0xa8, 0xf8, 0x59, 0x06, 0xe9, 0x57, 0x19,
	0xc0, 0xd4, 0x0f, 0x02, 0x95, 0x6f, 0x30, 0x02, 0x08, 0xcf, 0x9f, 0xc5, 0x12, 0x3f, 0xe7, 0xeb,
	0x69, 0xa0, 0x92, 0x59, 0xac, 0x62, 0x35, 0x23, 0x76, 0x9d, 0x47, 0x74, 0xa3, 0x0b, 0x9d, 0x8c,
	0xc7, 0xf8, 0x98, 0x0d, 0xae, 0x12, 0x8d, 0xdb, 0x77, 0x98, 0xe6, 0x01, 0x8e, 0x3f, 0xb0, 0xd3,
	0xb9, 0x31, 0x7b, 0x09, 0x10, 0x0a, 0xc8, 0x34, 0xbf, 0x62, 0x1d, 0x89, 0x90, 0x64, 0xb6, 0x35,
	0x6a, 0x4f, 0x06, 0x97, 0x17, 0xd3, 0x7f, 0xbc, 0x3a, 0x6d, 0x34, 0x79, 0x9b, 0x48, 0x2d, 0xfa,
	0x65, 0xe1, 0x98, 0x36, 0x61, 0x7e, 0xc6, 0xbf, 0xda, 0x07, 0xd6, 0x15, 0xc5, 0x1f, 0xb2, 0x96,
	0xe7, 0xda, 0xd6, 0xc8, 0x9a, 0xb4, 0x17, 0xdd, 0xb2, 0x70, 0x5a, 0x32, 0x14, 0x2d, 0xcf, 0xe5,
	0x8f, 0xd9, 0xd1, 0x52, 0x69, 0x19, 0x78, 0xae, 0xdd, 0xa2, 0xe2, 0xfd, 0xb2, 0x70, 0x7a, 0x58,
	0x49, 0x2b, 0x19, 0x8a, 0x3f, 0x45, 0x3e, 0x63, 0x6c, 0x1e, 0xa0, 0x54, 0x9b, 0xe5, 0x56, 0x83,
	0xdd, 0x1e, 0x59, 0x93, 0xfe, 0xe2, 0xb4, 0x2c, 0x9c, 0x81, 0x4f, 0xea, 0x0a, 0xb7, 0x1a, 0x44,
	0x03, 0x69, 0x34, 0xc8, 0x04, 0xec, 0x7b, 0xe4, 0x7d, 0xd0, 0x20, 0x93, 0xba, 0x41, 0x26, 0xcd,
	0x06, 0xb8, 0x41, 0xbb, 0xf3, 0xf7, 0x0b, 0x70, 0x83, 0xa2, 0x81, 0x54, 0xd1, 0xe7, 0x01, 0xaa,
	0xd4, 0x73, 0xed, 0x6e, 0x1d, 0xdd, 0xaf, 0x24, 0x8a, 0xbe, 0x2f, 0xf2, 0xa7, 0xac, 0x4f, 0x47,
	0x4a, 0x7e, 0x44, 0xbe, 0x27, 0x65, 0xe1, 0x30, 0x43, 0x52, 0xf0, 0x1a, 0xe0, 0x4f, 0x58, 0x6f,
	0xe9, 0xa7, 0x31, 0xa0, 0xe7, 0xda, 0x3d, 0xb2, 0x3d, 0x2e, 0x0b, 0xa7, 0x8f, 0xa4, 0x55, 0xbe,
	0xb7, 0xe5, 0x2a, 0xb1, 0x39, 0x93, 0x73, 0xbf, 0x4e, 0xbc, 0x87, 0xcd, 0x7f, 0x52, 0x23, 0x55,
	0x92, 0x17, 0x29, 0xf8, 0x08, 0xe1, 0x1c, 0x6d, 0x46, 0xe6, 0x94, 0x24, 0x30, 0xe2, 0xca, 0x47,
	0x51, 0x03, 0x15, 0xfd, 0x5e, 0x87, 0x7b, 0x7a, 0x50, 0xd3, 0xb9, 0x11, 0x89, 0xbe, 0x05, 0xc6,
	0xdf, 0xd8, 0xc9, 0xc1, 0x3a, 0x5d, 0x37, 0x47, 0x6b, 0xfd, 0x6f, 0xb4, 0x0e, 0xeb, 0xbc, 0x96,
	0x89, 0x44, 0x5a, 0x80, 0x8e, 0xd9, 0xa7, 0x2f, 0x95, 0x20, 0x8c, 0xce, 0xc7, 0xac, 0xfb, 0x26,
	0x8a, 0x32, 0x40, 0x9a, 0x7b, 0x67, 0xc1, 0xca, 0xc2, 0xe9, 0x2a, 0x52, 0xc4, 0xbe, 0x72, 0xa9,
	0xd8, 0xa0, 0xf1, 0x3c, 0xff, 0xc4, 0xce, 0x5e, 0x01, 0x36, 0x94, 0xb7, 0x7e, 0x0c, 0x21, 0x7f,
	0x74, 0xd7, 0x46, 0x0b, 0xb8, 0x3e, 0xbf, 0xb8, 0x1b, 0xca, 0xf4, 0xe2, 0xc1, 0xf7, 0xdd, 0xd0,
	0xfa, 0xb1, 0x1b, 0x5a, 0x3f, 0x77, 0x43, 0xeb, 0x63, 0xdb, 0xd7, 0x72, 0xdd, 0xa5, 0xef, 0xec,
	0xf9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x20, 0x45, 0xa3, 0x09, 0xb7, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountFeedClient is the client API for AccountFeed service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountFeedClient interface {
	GetAccountFeedPaged(ctx context.Context, in *AccountFeedReq, opts ...grpc.CallOption) (*AccountFeedResp, error)
}

type accountFeedClient struct {
	cc *grpc.ClientConn
}

func NewAccountFeedClient(cc *grpc.ClientConn) AccountFeedClient {
	return &accountFeedClient{cc}
}

func (c *accountFeedClient) GetAccountFeedPaged(ctx context.Context, in *AccountFeedReq, opts ...grpc.CallOption) (*AccountFeedResp, error) {
	out := new(AccountFeedResp)
	err := c.cc.Invoke(ctx, "/service.accountfeed.AccountFeed/GetAccountFeedPaged", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountFeedServer is the server API for AccountFeed service.
type AccountFeedServer interface {
	GetAccountFeedPaged(context.Context, *AccountFeedReq) (*AccountFeedResp, error)
}

// UnimplementedAccountFeedServer can be embedded to have forward compatible implementations.
type UnimplementedAccountFeedServer struct {
}

func (*UnimplementedAccountFeedServer) GetAccountFeedPaged(ctx context.Context, req *AccountFeedReq) (*AccountFeedResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountFeedPaged not implemented")
}

func RegisterAccountFeedServer(s *grpc.Server, srv AccountFeedServer) {
	s.RegisterService(&_AccountFeed_serviceDesc, srv)
}

func _AccountFeed_GetAccountFeedPaged_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountFeedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountFeedServer).GetAccountFeedPaged(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.accountfeed.AccountFeed/GetAccountFeedPaged",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountFeedServer).GetAccountFeedPaged(ctx, req.(*AccountFeedReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountFeed_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.accountfeed.AccountFeed",
	HandlerType: (*AccountFeedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccountFeedPaged",
			Handler:    _AccountFeed_GetAccountFeedPaged_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb.proto",
}

func (m *EmptyStruct) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmptyStruct) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EmptyStruct) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func (m *AccountFeedResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountFeedResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccountFeedResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPb(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *AccountFeedInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountFeedInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccountFeedInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.UpdatedAt != 0 {
		i = encodeVarintPb(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x58
	}
	if m.CreatedAt != 0 {
		i = encodeVarintPb(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x50
	}
	if len(m.TargetType) > 0 {
		i -= len(m.TargetType)
		copy(dAtA[i:], m.TargetType)
		i = encodeVarintPb(dAtA, i, uint64(len(m.TargetType)))
		i--
		dAtA[i] = 0x4a
	}
	if m.TargetID != 0 {
		i = encodeVarintPb(dAtA, i, uint64(m.TargetID))
		i--
		dAtA[i] = 0x40
	}
	if len(m.ActorType) > 0 {
		i -= len(m.ActorType)
		copy(dAtA[i:], m.ActorType)
		i = encodeVarintPb(dAtA, i, uint64(len(m.ActorType)))
		i--
		dAtA[i] = 0x3a
	}
	if m.ActorID != 0 {
		i = encodeVarintPb(dAtA, i, uint64(m.ActorID))
		i--
		dAtA[i] = 0x30
	}
	if len(m.ActionText) > 0 {
		i -= len(m.ActionText)
		copy(dAtA[i:], m.ActionText)
		i = encodeVarintPb(dAtA, i, uint64(len(m.ActionText)))
		i--
		dAtA[i] = 0x2a
	}
	if m.ActionTime != 0 {
		i = encodeVarintPb(dAtA, i, uint64(m.ActionTime))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ActionType) > 0 {
		i -= len(m.ActionType)
		copy(dAtA[i:], m.ActionType)
		i = encodeVarintPb(dAtA, i, uint64(len(m.ActionType)))
		i--
		dAtA[i] = 0x1a
	}
	if m.TopicID != 0 {
		i = encodeVarintPb(dAtA, i, uint64(m.TopicID))
		i--
		dAtA[i] = 0x10
	}
	if m.ID != 0 {
		i = encodeVarintPb(dAtA, i, uint64(m.ID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AccountFeedReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountFeedReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccountFeedReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Offset != 0 {
		i = encodeVarintPb(dAtA, i, uint64(m.Offset))
		i--
		dAtA[i] = 0x18
	}
	if m.Limit != 0 {
		i = encodeVarintPb(dAtA, i, uint64(m.Limit))
		i--
		dAtA[i] = 0x10
	}
	if m.TopicID != 0 {
		i = encodeVarintPb(dAtA, i, uint64(m.TopicID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPb(dAtA []byte, offset int, v uint64) int {
	offset -= sovPb(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EmptyStruct) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *AccountFeedResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovPb(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *AccountFeedInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovPb(uint64(m.ID))
	}
	if m.TopicID != 0 {
		n += 1 + sovPb(uint64(m.TopicID))
	}
	l = len(m.ActionType)
	if l > 0 {
		n += 1 + l + sovPb(uint64(l))
	}
	if m.ActionTime != 0 {
		n += 1 + sovPb(uint64(m.ActionTime))
	}
	l = len(m.ActionText)
	if l > 0 {
		n += 1 + l + sovPb(uint64(l))
	}
	if m.ActorID != 0 {
		n += 1 + sovPb(uint64(m.ActorID))
	}
	l = len(m.ActorType)
	if l > 0 {
		n += 1 + l + sovPb(uint64(l))
	}
	if m.TargetID != 0 {
		n += 1 + sovPb(uint64(m.TargetID))
	}
	l = len(m.TargetType)
	if l > 0 {
		n += 1 + l + sovPb(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovPb(uint64(m.CreatedAt))
	}
	if m.UpdatedAt != 0 {
		n += 1 + sovPb(uint64(m.UpdatedAt))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *AccountFeedReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TopicID != 0 {
		n += 1 + sovPb(uint64(m.TopicID))
	}
	if m.Limit != 0 {
		n += 1 + sovPb(uint64(m.Limit))
	}
	if m.Offset != 0 {
		n += 1 + sovPb(uint64(m.Offset))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovPb(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPb(x uint64) (n int) {
	return sovPb(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EmptyStruct) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmptyStruct: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmptyStruct: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountFeedResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountFeedResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountFeedResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, &AccountFeedInfo{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountFeedInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountFeedInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountFeedInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TopicID", wireType)
			}
			m.TopicID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TopicID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActionType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionTime", wireType)
			}
			m.ActionTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionText", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActionText = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActorID", wireType)
			}
			m.ActorID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActorID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActorType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActorType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetID", wireType)
			}
			m.TargetID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountFeedReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountFeedReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountFeedReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TopicID", wireType)
			}
			m.TopicID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TopicID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Offset", wireType)
			}
			m.Offset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Offset |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPb(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPb
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPb
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthPb
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowPb
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipPb(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthPb
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthPb = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPb   = fmt.Errorf("proto: integer overflow")
)
