pollTimeout = "30s"
pathCache = "/tmp/"

[wardenServer]
    addr = "0.0.0.0:8099"
    timeout = "1s"

[ecode]
    domain = "localhost:6401"

[db.auth]
    addr = "mysql:3306"
    dsn = "flywk:flywk@tcp(localhost:3306)/auth_uat?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4"
    active = 5
    idle = 2
    queryTimeout = "1s"
    execTimeout = "2s"
    tranTimeout = "2s"
    [db.auth.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
[db.main]
    addr = "mysql:3306"
    dsn = "flywk:flywk@tcp(localhost:3306)/flywk_uat?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4"
    active = 5
    idle = 2
    queryTimeout = "1s"
    execTimeout = "2s"
    tranTimeout = "2s"
    [db.main.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100


[mars]
    address = "0.0.0.0:8000"
    maxListen = 10
    timeout="2s"

[memcache.auth]
  expire = "24h"
  name = "valerian-auth"
  proto = "tcp"
  addr = "localhost:11211"
  active = 50
  idle = 10
  dialTimeout = "1s"
  readTimeout = "1s"
  writeTimeout = "1s"
  idleTimeout = "10s"
[memcache.main]
  expire = "24h"
  name = "valerian-main"
  proto = "tcp"
  addr = "localhost:11211"
  active = 50
  idle = 10
  dialTimeout = "1s"
  readTimeout = "1s"
  writeTimeout = "1s"
  idleTimeout = "10s"


[ConfSvr]
timeout = "1s"

[discovery]
    nodes = ["192.168.0.136:7171"]
    key = "6a29f8ed87407c11"
    secret = "d3c5a85f5b895a03735b5d20a273bc57"
    env = "uat"
    zone = "hz001"