basePath: /api/v1
definitions:
  models.LoginReq:
    properties:
      identity:
        description: Identity 登录标识，可以传入邮件或手机号，请在提交前进行验证
        type: string
      password:
        description: Password 密码，服务端不保存密码的明文值，请在提交前进行 MD5 哈希
        type: string
    required:
    - identity
    - password
    type: object
  models.LoginResult:
    properties:
      role:
        description: 用户角色，用于客户端权限管理
        type: string
      token:
        description: |-
          Token JWT Token， 请在 HTTP 请求头中添加
          例子： Authorization: Bearer  TJVA95OrM7E20RMHrHDcEfxjoYZgeFONFh7HgQ
        type: string
    type: object
host: www.flywk.com
info:
  contact: {}
  description: 飞行百科 API
  license: {}
  version: "1.0"
paths:
  /session:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 用户登录
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.LoginReq'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/models.LoginResult'
            type: object
        "400":
          description: 验证失败
        "500":
          description: 服务器端错误
      summary: 用户登录
      tags:
      - session
swagger: "2.0"
