basePath: /api/v1
definitions:
  model.ArgDigitLogin:
    properties:
      client_id:
        description: ClientID
        type: string
      mobile:
        description: 手机号码
        type: string
      prefix:
        description: Prefix 国际区号，例如86
        type: string
      source:
        description: Source 来源，1:Web, 2:iOS; 3:Android
        type: integer
      valcode:
        description: 验证码 6位数字
        type: string
    type: object
  model.ArgEmailLogin:
    properties:
      client_id:
        description: ClientID OAUTH2 Client ID
        type: string
      email:
        description: Email 邮件地址
        type: string
      password:
        description: Password 密码，长度至少为6位
        type: string
      source:
        description: Source 来源，1:Web, 2:iOS; 3:Android
        type: integer
    type: object
  model.ArgMobileLogin:
    properties:
      client_id:
        description: ClientID
        type: string
      mobile:
        description: Mobile 手机号码
        type: string
      password:
        description: Password 密码
        type: string
      prefix:
        description: Prefix 国际区号，例如86
        type: string
      source:
        description: Source 来源，1:Web, 2:iOS; 3:Android
        type: integer
    type: object
  model.LoginResp:
    properties:
      access_token:
        description: |-
          Access Token， 请在 HTTP 请求头中添加
          例子： Authorization: Bearer  TJVA95OrM7E20RMHrHDcEfxjoYZgeFONFh7HgQ
        type: string
      account_id:
        description: 用户ID
        type: string
      expires_in:
        description: 有效期 秒为单位
        type: integer
      profile:
        $ref: '#/definitions/model.Profile'
        type: object
      refresh_token:
        description: Refresh Token 暂不使用
        type: string
      role:
        description: 用户角色，用于客户端权限管理
        type: string
      scope:
        description: Scope 暂不使用
        type: string
      token_type:
        description: Token 类型，默认为 Bearer
        type: string
    type: object
  model.Profile:
    properties:
      avatar:
        description: 头像
        type: string
      birth_day:
        description: 出生日
        type: integer
      birth_month:
        description: 出生月
        type: integer
      birth_year:
        description: 出生年
        type: integer
      created_at:
        description: 注册时间
        type: integer
      email:
        description: 邮件地址
        format: email
        type: string
      gender:
        description: 性别 1为男， 2为女
        type: integer
      id:
        description: ID
        format: int64
        type: string
      id_cert:
        description: 是否身份认证
        type: boolean
      introduction:
        description: 自我介绍
        type: string
      ip:
        description: IP 注册IP
        type: string
      is_org:
        description: 是否机构用户
        type: boolean
      is_vip:
        description: 是否VIP
        type: boolean
      location:
        description: 所在地区值
        type: integer
      location_string:
        description: 所在地区名，地区是层级结构，这里将国家、州/省、市、区全部获取出来
        type: string
      mobile:
        description: 手机
        format: mobile
        type: string
      role:
        type: string
      source:
        description: 来源，1:Web, 2:iOS; 3:Android
        type: integer
      updated_at:
        description: 更新时间
        type: integer
      user_name:
        description: 用户名
        format: user_name
        type: string
      work_cert:
        description: 是否工作认证
        type: boolean
    type: object
host: dev.flywk.com
info:
  contact: {}
  description: |+
    飞行百科 API
    所有返回结果以如下JSON对象返回
    <pre>
    {
    "code": 0,           // 如果没有另行约定，一般为200
    "message": "string", // 一般用户发生错误或者验证失败时候返回的消息
    "result": {},        // 返回结果，所有文档所示的返回结果处于这个字段
    "success": true      // 用于判断是否执行成功
    }
    </pre>

  license: {}
  title: 飞行百科 API
  version: "1.0"
paths:
  /oauth/login/digit:
    post:
      consumes:
      - application/json
      description: 验证码登录
      parameters:
      - description: Source 来源，1:Web, 2:iOS; 3:Android
        enum:
        - 1
        - 2
        - 3
        in: header
        name: Source
        required: true
        type: integer
      - description: 语言
        enum:
        - zh-CN
        - en-US
        in: header
        name: Locale
        required: true
        type: string
      - description: 手机登录
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/model.ArgDigitLogin'
          type: object
      produces:
      - application/json
      responses:
        "2":
          description: 验证码已失效
        "3":
          description: 验证码错误
        "5":
          description: 未找到地址信息
        "116":
          description: Client 不存在
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.LoginResp'
            type: object
        "401":
          description: 验证失败
        "626":
          description: 用户不存在
      summary: 验证码登录
      tags:
      - auth
  /oauth/login/email:
    post:
      consumes:
      - application/json
      description: 用户邮件登录
      parameters:
      - description: 来源
        enum:
        - 1
        - 2
        - 3
        in: header
        name: Source
        required: true
        type: integer
      - description: 语言
        enum:
        - zh-CN
        - en-US
        in: header
        name: Locale
        required: true
        type: string
      - description: 用户登录
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/model.ArgEmailLogin'
          type: object
      produces:
      - application/json
      responses:
        "5":
          description: 未找到地址信息
        "116":
          description: Client 不存在
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.LoginResp'
            type: object
        "401":
          description: 验证失败
        "500":
          description: 服务器端错误
        "626":
          description: 用户不存在
        "629":
          description: 密码错误
      summary: 用户邮件登录
      tags:
      - auth
  /oauth/login/mobile:
    post:
      consumes:
      - application/json
      description: 用户手机登录
      parameters:
      - description: Source 来源，1:Web, 2:iOS; 3:Android
        enum:
        - 1
        - 2
        - 3
        in: header
        name: Source
        required: true
        type: integer
      - description: 语言
        enum:
        - zh-CN
        - en-US
        in: header
        name: Locale
        required: true
        type: string
      - description: 手机登录
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/model.ArgMobileLogin'
          type: object
      produces:
      - application/json
      responses:
        "5":
          description: 未找到地址信息
        "116":
          description: Client 不存在
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.LoginResp'
            type: object
        "401":
          description: 验证失败
        "500":
          description: 服务器端错误
        "626":
          description: 用户不存在
        "629":
          description: 密码错误
      summary: 用户手机登录
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
