stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: fetch


service-msm-build:
  stage: build
  tags:
    - valerian
  before_script:
    - cd $GOPATH/src
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME/app/service/msm/cmd
  script:
    # Compile and name the binary as `hello`
    - GO111MODULE=on go build -mod vendor

service-msm-test:
  stage: test
  tags:
    - valerian
  before_script:
    - cd $GOPATH/src
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME/app/service/msm
  script:
    # Compile and name the binary as `hello`
    - go test ./...

interface-locale-build:
  stage: build
  tags:
    - valerian
  before_script:
    - cd $GOPATH/src
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME/app/interface/locale/cmd
  script:
    # Compile and name the binary as `hello`
    - GO111MODULE=on go build -mod vendor

service-locale-test:
interface-locale-build:
  stage: test
  tags:
    - valerian
  before_script:
    - cd $GOPATH/src
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME/app/interface/locale
  script:
    # Compile and name the binary as `hello`
    - go test ./...