image: registry-vpc.cn-hangzhou.aliyuncs.com/flywk/gobuild:latest
stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: fetch
  GIT_DEPTH: 10


service-msm-build:
  stage: build
  tags:
    - valerian
  before_script:
    - cd $GOPATH/src
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_DIR
  script:
    # Compile and name the binary as `hello`
    - make build-service-msm

service-msm-test:
  stage: test
  tags:
    - valerian
  before_script:
    - cd $GOPATH/src
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME/app/service/msm
  script:
    # Compile and name the binary as `hello`
    - go env -w GOPROXY=https://goproxy.cn,direct
    - GO111MODULE=on CGO_ENABLED=0 GOOS=linux go test -mod vendor ./...
  dependencies:
    - service-msm-build

