stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: fetch


service-msm-build:
  stage: build
  tags:
    - valerian
  before_script:
    - cd $GOPATH/src
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME/app/service/msm/cmd
  script:
    # Compile and name the binary as `hello`
    - GO111MODULE=on go build -mod vendor

service-msm-test:
  stage: test
  tags:
    - valerian
  before_script:
    - cd $GOPATH/src
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME/app/service/msm
  script:
    # Compile and name the binary as `hello`
    - go env -w GOPROXY=https://goproxy.cn,direct
    - go test ./...
  dependencies:
    - service-msm-build

interface-locale-build:
  stage: build
  tags:
    - valerian
  before_script:
    - cd $GOPATH/src
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME/app/interface/locale/cmd
  script:
    # Compile and name the binary as `hello`
    - GO111MODULE=on go build -mod vendor

interface-locale-test:
  stage: test
  tags:
    - valerian
  before_script:
    - cd $GOPATH/src
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME/app/interface/locale
  script:
    # Compile and name the binary as `hello`
    - go env -w GOPROXY=https://goproxy.cn,direct
    - go test ./...
  dependencies:
    - interface-locale-build

interface-location-build:
  stage: build
  tags:
    - valerian
  before_script:
    - cd $GOPATH/src
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME/app/interface/location/cmd
  script:
    # Compile and name the binary as `hello`
    - GO111MODULE=on go build -mod vendor

interface-location-test:
  stage: test
  tags:
    - valerian
  before_script:
    - cd $GOPATH/src
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME/app/interface/location
  script:
    # Compile and name the binary as `hello`
    - go env -w GOPROXY=https://goproxy.cn,direct
    - go test ./...
  dependencies:
    - interface-location-build
