settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: api
  path: .
  env:
      APP_ID: valerian
  commands:
    build:
      status: true
      dir: ./
    run:
      status: true
      dir: ./
  args:
  - -conf=./app.toml
  watcher:
    paths:
    - /
    extensions:
    - go
    ignored_paths:
    - .git
    - .realize
    - vendor
