development:
    dialect: mysql
    datasource: flywk:flywk@/flywk_dev?parseTime=true
    dir: migrations
    table: migrations

production:
    dialect: mysql
    datasource: flywk:flywk@/flywk_prod?parseTime=true
    dir: migrations
    table: migrations

