version = "1.0.0"
user = "nobody"
pid = "/tmp/discovery.pid"
dir = "./"

nodes = ["127.0.0.1:7171", "127.0.0.1:7172"]

[zones]

[log]
dir = "/data/log/discovery/"

[mars]
    [mars.inner]
    address = "0.0.0.0:7172"
    timeout = "40s"

[identify]
    [identify.host]
    auth = "http://passport.stonote.loc"
    secret = "http://open.stonote.loc"
    [identify.httpClient]
    key = "0c4b8fe3ff35a4b6"
    secret = "b370880d1aca7d3a289b9b9a7f4d6812"
    dial = "30ms"
    timeout = "100ms"
    keepAlive = "60s"
    [identify.httpClient.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [identify.httpClient.url]
    "http://passport.stonote.loc/intranet/auth/tokenInfo" = {timeout = "100ms"}
    "http://passport.stonote.loc/intranet/auth/cookieInfo" = {timeout = "100ms"}
    "http://open.stonote.loc/api/getsecret" = {timeout = "500ms"}

[httpClient]
key = "0c4b8fe3ff35a4b6"
secret = "b370880d1aca7d3a289b9b9a7f4d6812"
dial = "500ms"
timeout = "1s"
keepAlive = "60s"
    [httpClient.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

