apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-uat-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: alicloud-disk-efficiency