// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb.proto

package api

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BaseInfoReply struct {
	ID       int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"id"`
	UserName string `protobuf:"bytes,2,opt,name=UserName,proto3" json:"user_name"`
	// Types that are valid to be assigned to Gender:
	//	*BaseInfoReply_GenderValue
	Gender isBaseInfoReply_Gender `protobuf_oneof:"Gender"`
	// Types that are valid to be assigned to Introduction:
	//	*BaseInfoReply_IntroductionValue
	Introduction         isBaseInfoReply_Introduction `protobuf_oneof:"Introduction"`
	Avatar               string                       `protobuf:"bytes,5,opt,name=Avatar,proto3" json:"avatar"`
	IDCert               bool                         `protobuf:"varint,6,opt,name=IDCert,proto3" json:"id_cert"`
	WorkCert             bool                         `protobuf:"varint,7,opt,name=WorkCert,proto3" json:"work_cert"`
	IsOrg                bool                         `protobuf:"varint,8,opt,name=IsOrg,proto3" json:"is_org"`
	IsVIP                bool                         `protobuf:"varint,9,opt,name=IsVIP,proto3" json:"is_vip"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *BaseInfoReply) Reset()         { *m = BaseInfoReply{} }
func (m *BaseInfoReply) String() string { return proto.CompactTextString(m) }
func (*BaseInfoReply) ProtoMessage()    {}
func (*BaseInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}
func (m *BaseInfoReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BaseInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BaseInfoReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BaseInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfoReply.Merge(m, src)
}
func (m *BaseInfoReply) XXX_Size() int {
	return m.Size()
}
func (m *BaseInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfoReply proto.InternalMessageInfo

type isBaseInfoReply_Gender interface {
	isBaseInfoReply_Gender()
	MarshalTo([]byte) (int, error)
	Size() int
}
type isBaseInfoReply_Introduction interface {
	isBaseInfoReply_Introduction()
	MarshalTo([]byte) (int, error)
	Size() int
}

type BaseInfoReply_GenderValue struct {
	GenderValue int32 `protobuf:"varint,3,opt,name=GenderValue,proto3,oneof" json:"gender"`
}
type BaseInfoReply_IntroductionValue struct {
	IntroductionValue string `protobuf:"bytes,4,opt,name=IntroductionValue,proto3,oneof" json:"introduction"`
}

func (*BaseInfoReply_GenderValue) isBaseInfoReply_Gender()             {}
func (*BaseInfoReply_IntroductionValue) isBaseInfoReply_Introduction() {}

func (m *BaseInfoReply) GetGender() isBaseInfoReply_Gender {
	if m != nil {
		return m.Gender
	}
	return nil
}
func (m *BaseInfoReply) GetIntroduction() isBaseInfoReply_Introduction {
	if m != nil {
		return m.Introduction
	}
	return nil
}

func (m *BaseInfoReply) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *BaseInfoReply) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *BaseInfoReply) GetGenderValue() int32 {
	if x, ok := m.GetGender().(*BaseInfoReply_GenderValue); ok {
		return x.GenderValue
	}
	return 0
}

func (m *BaseInfoReply) GetIntroductionValue() string {
	if x, ok := m.GetIntroduction().(*BaseInfoReply_IntroductionValue); ok {
		return x.IntroductionValue
	}
	return ""
}

func (m *BaseInfoReply) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *BaseInfoReply) GetIDCert() bool {
	if m != nil {
		return m.IDCert
	}
	return false
}

func (m *BaseInfoReply) GetWorkCert() bool {
	if m != nil {
		return m.WorkCert
	}
	return false
}

func (m *BaseInfoReply) GetIsOrg() bool {
	if m != nil {
		return m.IsOrg
	}
	return false
}

func (m *BaseInfoReply) GetIsVIP() bool {
	if m != nil {
		return m.IsVIP
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BaseInfoReply) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BaseInfoReply_GenderValue)(nil),
		(*BaseInfoReply_IntroductionValue)(nil),
	}
}

type BaseInfosReply struct {
	// member基本信息集合
	BaseInfos            map[int64]*BaseInfoReply `protobuf:"bytes,1,rep,name=base_infos,json=baseInfos,proto3" json:"base_infos,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *BaseInfosReply) Reset()         { *m = BaseInfosReply{} }
func (m *BaseInfosReply) String() string { return proto.CompactTextString(m) }
func (*BaseInfosReply) ProtoMessage()    {}
func (*BaseInfosReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1}
}
func (m *BaseInfosReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BaseInfosReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BaseInfosReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BaseInfosReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfosReply.Merge(m, src)
}
func (m *BaseInfosReply) XXX_Size() int {
	return m.Size()
}
func (m *BaseInfosReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfosReply.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfosReply proto.InternalMessageInfo

func (m *BaseInfosReply) GetBaseInfos() map[int64]*BaseInfoReply {
	if m != nil {
		return m.BaseInfos
	}
	return nil
}

type ProfileReply struct {
	ID       int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"id"`
	UserName string `protobuf:"bytes,2,opt,name=UserName,proto3" json:"user_name"`
	// Types that are valid to be assigned to Gender:
	//	*ProfileReply_GenderValue
	Gender isProfileReply_Gender `protobuf_oneof:"Gender"`
	// Types that are valid to be assigned to Introduction:
	//	*ProfileReply_IntroductionValue
	Introduction isProfileReply_Introduction `protobuf_oneof:"Introduction"`
	// Types that are valid to be assigned to Location:
	//	*ProfileReply_LocationValue
	Location isProfileReply_Location `protobuf_oneof:"Location"`
	// Types that are valid to be assigned to LocationString:
	//	*ProfileReply_LocationStringValue
	LocationString       isProfileReply_LocationString `protobuf_oneof:"LocationString"`
	Avatar               string                        `protobuf:"bytes,7,opt,name=Avatar,proto3" json:"avatar"`
	IDCert               bool                          `protobuf:"varint,8,opt,name=IDCert,proto3" json:"id_cert"`
	WorkCert             bool                          `protobuf:"varint,9,opt,name=WorkCert,proto3" json:"work_cert"`
	IsOrg                bool                          `protobuf:"varint,10,opt,name=IsOrg,proto3" json:"is_org"`
	IsVIP                bool                          `protobuf:"varint,11,opt,name=IsVIP,proto3" json:"is_vip"`
	Stat                 *AccountStatInfo              `protobuf:"bytes,12,opt,name=Stat,proto3" json:"stat"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ProfileReply) Reset()         { *m = ProfileReply{} }
func (m *ProfileReply) String() string { return proto.CompactTextString(m) }
func (*ProfileReply) ProtoMessage()    {}
func (*ProfileReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{2}
}
func (m *ProfileReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProfileReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProfileReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProfileReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileReply.Merge(m, src)
}
func (m *ProfileReply) XXX_Size() int {
	return m.Size()
}
func (m *ProfileReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileReply.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileReply proto.InternalMessageInfo

type isProfileReply_Gender interface {
	isProfileReply_Gender()
	MarshalTo([]byte) (int, error)
	Size() int
}
type isProfileReply_Introduction interface {
	isProfileReply_Introduction()
	MarshalTo([]byte) (int, error)
	Size() int
}
type isProfileReply_Location interface {
	isProfileReply_Location()
	MarshalTo([]byte) (int, error)
	Size() int
}
type isProfileReply_LocationString interface {
	isProfileReply_LocationString()
	MarshalTo([]byte) (int, error)
	Size() int
}

type ProfileReply_GenderValue struct {
	GenderValue int32 `protobuf:"varint,3,opt,name=GenderValue,proto3,oneof" json:"gender"`
}
type ProfileReply_IntroductionValue struct {
	IntroductionValue string `protobuf:"bytes,4,opt,name=IntroductionValue,proto3,oneof" json:"introduction"`
}
type ProfileReply_LocationValue struct {
	LocationValue int64 `protobuf:"varint,5,opt,name=LocationValue,proto3,oneof" json:"location"`
}
type ProfileReply_LocationStringValue struct {
	LocationStringValue string `protobuf:"bytes,6,opt,name=LocationStringValue,proto3,oneof" json:"location_string"`
}

func (*ProfileReply_GenderValue) isProfileReply_Gender()                 {}
func (*ProfileReply_IntroductionValue) isProfileReply_Introduction()     {}
func (*ProfileReply_LocationValue) isProfileReply_Location()             {}
func (*ProfileReply_LocationStringValue) isProfileReply_LocationString() {}

func (m *ProfileReply) GetGender() isProfileReply_Gender {
	if m != nil {
		return m.Gender
	}
	return nil
}
func (m *ProfileReply) GetIntroduction() isProfileReply_Introduction {
	if m != nil {
		return m.Introduction
	}
	return nil
}
func (m *ProfileReply) GetLocation() isProfileReply_Location {
	if m != nil {
		return m.Location
	}
	return nil
}
func (m *ProfileReply) GetLocationString() isProfileReply_LocationString {
	if m != nil {
		return m.LocationString
	}
	return nil
}

func (m *ProfileReply) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ProfileReply) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *ProfileReply) GetGenderValue() int32 {
	if x, ok := m.GetGender().(*ProfileReply_GenderValue); ok {
		return x.GenderValue
	}
	return 0
}

func (m *ProfileReply) GetIntroductionValue() string {
	if x, ok := m.GetIntroduction().(*ProfileReply_IntroductionValue); ok {
		return x.IntroductionValue
	}
	return ""
}

func (m *ProfileReply) GetLocationValue() int64 {
	if x, ok := m.GetLocation().(*ProfileReply_LocationValue); ok {
		return x.LocationValue
	}
	return 0
}

func (m *ProfileReply) GetLocationStringValue() string {
	if x, ok := m.GetLocationString().(*ProfileReply_LocationStringValue); ok {
		return x.LocationStringValue
	}
	return ""
}

func (m *ProfileReply) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *ProfileReply) GetIDCert() bool {
	if m != nil {
		return m.IDCert
	}
	return false
}

func (m *ProfileReply) GetWorkCert() bool {
	if m != nil {
		return m.WorkCert
	}
	return false
}

func (m *ProfileReply) GetIsOrg() bool {
	if m != nil {
		return m.IsOrg
	}
	return false
}

func (m *ProfileReply) GetIsVIP() bool {
	if m != nil {
		return m.IsVIP
	}
	return false
}

func (m *ProfileReply) GetStat() *AccountStatInfo {
	if m != nil {
		return m.Stat
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ProfileReply) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ProfileReply_GenderValue)(nil),
		(*ProfileReply_IntroductionValue)(nil),
		(*ProfileReply_LocationValue)(nil),
		(*ProfileReply_LocationStringValue)(nil),
	}
}

type AccountStatInfo struct {
	Following            int32    `protobuf:"varint,1,opt,name=Following,proto3" json:"following"`
	Fans                 int32    `protobuf:"varint,2,opt,name=Fans,proto3" json:"fans"`
	Black                int32    `protobuf:"varint,3,opt,name=Black,proto3" json:"black"`
	TopicCount           int32    `protobuf:"varint,4,opt,name=TopicCount,proto3" json:"topic_count"`
	ArticleCount         int32    `protobuf:"varint,5,opt,name=ArticleCount,proto3" json:"article_count"`
	DiscussionCount      int32    `protobuf:"varint,6,opt,name=DiscussionCount,proto3" json:"discussion_count"`
	IsFollowing          bool     `protobuf:"varint,7,opt,name=IsFollowing,proto3" json:"is_following"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountStatInfo) Reset()         { *m = AccountStatInfo{} }
func (m *AccountStatInfo) String() string { return proto.CompactTextString(m) }
func (*AccountStatInfo) ProtoMessage()    {}
func (*AccountStatInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{3}
}
func (m *AccountStatInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountStatInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountStatInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountStatInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountStatInfo.Merge(m, src)
}
func (m *AccountStatInfo) XXX_Size() int {
	return m.Size()
}
func (m *AccountStatInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountStatInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountStatInfo proto.InternalMessageInfo

func (m *AccountStatInfo) GetFollowing() int32 {
	if m != nil {
		return m.Following
	}
	return 0
}

func (m *AccountStatInfo) GetFans() int32 {
	if m != nil {
		return m.Fans
	}
	return 0
}

func (m *AccountStatInfo) GetBlack() int32 {
	if m != nil {
		return m.Black
	}
	return 0
}

func (m *AccountStatInfo) GetTopicCount() int32 {
	if m != nil {
		return m.TopicCount
	}
	return 0
}

func (m *AccountStatInfo) GetArticleCount() int32 {
	if m != nil {
		return m.ArticleCount
	}
	return 0
}

func (m *AccountStatInfo) GetDiscussionCount() int32 {
	if m != nil {
		return m.DiscussionCount
	}
	return 0
}

func (m *AccountStatInfo) GetIsFollowing() bool {
	if m != nil {
		return m.IsFollowing
	}
	return false
}

type AidReq struct {
	Aid                  int64    `protobuf:"varint,1,opt,name=aid,proto3" json:"aid"`
	RemoteIP             string   `protobuf:"bytes,2,opt,name=remoteIP,proto3" json:"remoteIP"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AidReq) Reset()         { *m = AidReq{} }
func (m *AidReq) String() string { return proto.CompactTextString(m) }
func (*AidReq) ProtoMessage()    {}
func (*AidReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{4}
}
func (m *AidReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AidReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AidReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AidReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AidReq.Merge(m, src)
}
func (m *AidReq) XXX_Size() int {
	return m.Size()
}
func (m *AidReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AidReq.DiscardUnknown(m)
}

var xxx_messageInfo_AidReq proto.InternalMessageInfo

func (m *AidReq) GetAid() int64 {
	if m != nil {
		return m.Aid
	}
	return 0
}

func (m *AidReq) GetRemoteIP() string {
	if m != nil {
		return m.RemoteIP
	}
	return ""
}

type AidsReq struct {
	// aid 列表
	Aids                 []int64  `protobuf:"varint,1,rep,packed,name=aids,proto3" json:"aids"`
	RemoteIP             string   `protobuf:"bytes,2,opt,name=remoteIP,proto3" json:"remoteIP"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AidsReq) Reset()         { *m = AidsReq{} }
func (m *AidsReq) String() string { return proto.CompactTextString(m) }
func (*AidsReq) ProtoMessage()    {}
func (*AidsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{5}
}
func (m *AidsReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AidsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AidsReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AidsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AidsReq.Merge(m, src)
}
func (m *AidsReq) XXX_Size() int {
	return m.Size()
}
func (m *AidsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AidsReq.DiscardUnknown(m)
}

var xxx_messageInfo_AidsReq proto.InternalMessageInfo

func (m *AidsReq) GetAids() []int64 {
	if m != nil {
		return m.Aids
	}
	return nil
}

func (m *AidsReq) GetRemoteIP() string {
	if m != nil {
		return m.RemoteIP
	}
	return ""
}

func init() {
	proto.RegisterType((*BaseInfoReply)(nil), "service.account.BaseInfoReply")
	proto.RegisterType((*BaseInfosReply)(nil), "service.account.BaseInfosReply")
	proto.RegisterMapType((map[int64]*BaseInfoReply)(nil), "service.account.BaseInfosReply.BaseInfosEntry")
	proto.RegisterType((*ProfileReply)(nil), "service.account.ProfileReply")
	proto.RegisterType((*AccountStatInfo)(nil), "service.account.AccountStatInfo")
	proto.RegisterType((*AidReq)(nil), "service.account.AidReq")
	proto.RegisterType((*AidsReq)(nil), "service.account.AidsReq")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_f80abaa17e25ccc8) }

var fileDescriptor_f80abaa17e25ccc8 = []byte{
	// 855 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0xcf, 0x6f, 0xe3, 0x44,
	0x14, 0xc6, 0x49, 0xec, 0x38, 0x2f, 0x69, 0xd3, 0xce, 0x22, 0x30, 0xd5, 0xaa, 0x8e, 0xc2, 0x25,
	0x08, 0x91, 0x4a, 0x65, 0x91, 0x10, 0x87, 0x15, 0xf1, 0x86, 0x6e, 0x2c, 0xb1, 0x50, 0x66, 0x61,
	0x91, 0x10, 0x52, 0x34, 0xb1, 0x27, 0x61, 0xd4, 0xd4, 0x13, 0x66, 0x9c, 0xae, 0xfa, 0x8f, 0xf0,
	0xdf, 0x70, 0xe7, 0xc8, 0x95, 0x8b, 0x05, 0x3d, 0xfa, 0xc8, 0x5f, 0x80, 0xfc, 0xc6, 0x69, 0x92,
	0xfe, 0x50, 0x7b, 0xe5, 0xe2, 0xcc, 0xbc, 0xef, 0xfb, 0xe6, 0xcd, 0xbc, 0xf7, 0xcd, 0x04, 0xdc,
	0xc5, 0xa4, 0xbf, 0x50, 0x32, 0x95, 0xa4, 0xad, 0xb9, 0xba, 0x10, 0x11, 0xef, 0xb3, 0x28, 0x92,
	0xcb, 0x24, 0x3d, 0xf8, 0x64, 0x26, 0xd2, 0x5f, 0x96, 0x93, 0x7e, 0x24, 0xcf, 0x8f, 0x66, 0x72,
	0x26, 0x8f, 0x90, 0x37, 0x59, 0x4e, 0x71, 0x86, 0x13, 0x1c, 0x19, 0x7d, 0xf7, 0xb7, 0x2a, 0xec,
	0x04, 0x4c, 0xf3, 0x30, 0x99, 0x4a, 0xca, 0x17, 0xf3, 0x4b, 0xf2, 0x1e, 0x54, 0xc2, 0xa1, 0x67,
	0x75, 0xac, 0x5e, 0x35, 0x70, 0xf2, 0xcc, 0xaf, 0x88, 0x98, 0x56, 0xc2, 0x21, 0xf9, 0x08, 0xdc,
	0x1f, 0x34, 0x57, 0xdf, 0xb0, 0x73, 0xee, 0x55, 0x3a, 0x56, 0xaf, 0x11, 0xec, 0xe4, 0x99, 0xdf,
	0x58, 0x6a, 0xae, 0xc6, 0x09, 0x3b, 0xe7, 0xf4, 0x1a, 0x26, 0x7d, 0x68, 0xbe, 0xe4, 0x49, 0xcc,
	0xd5, 0x1b, 0x36, 0x5f, 0x72, 0xaf, 0xda, 0xb1, 0x7a, 0x76, 0x00, 0x79, 0xe6, 0x3b, 0x33, 0x0c,
	0x8f, 0xde, 0xa1, 0x9b, 0x04, 0xf2, 0x25, 0xec, 0x87, 0x49, 0xaa, 0x64, 0xbc, 0x8c, 0x52, 0x21,
	0x13, 0xa3, 0xaa, 0x61, 0x8e, 0xbd, 0x3c, 0xf3, 0x5b, 0x62, 0x03, 0x1c, 0x59, 0xf4, 0x36, 0x99,
	0x74, 0xc1, 0x19, 0x5c, 0xb0, 0x94, 0x29, 0xcf, 0x46, 0x19, 0x26, 0x63, 0x18, 0xa1, 0x25, 0x42,
	0x3e, 0x04, 0x27, 0x1c, 0xbe, 0xe0, 0x2a, 0xf5, 0x9c, 0x8e, 0xd5, 0x73, 0x83, 0x66, 0x9e, 0xf9,
	0x75, 0x11, 0x8f, 0x23, 0xae, 0x52, 0x5a, 0x42, 0xc5, 0x29, 0x7f, 0x94, 0xea, 0x0c, 0x69, 0x75,
	0xa4, 0xe1, 0x29, 0xdf, 0x4a, 0x75, 0x66, 0x88, 0xd7, 0x30, 0xe9, 0x80, 0x1d, 0xea, 0x6f, 0xd5,
	0xcc, 0x73, 0x91, 0x87, 0x29, 0x85, 0x1e, 0x4b, 0x35, 0xa3, 0x06, 0x30, 0x8c, 0x37, 0xe1, 0xa9,
	0xd7, 0xd8, 0x62, 0x5c, 0x88, 0x05, 0x35, 0x40, 0xe0, 0x82, 0x63, 0x0a, 0x11, 0xec, 0x42, 0x6b,
	0xf3, 0x58, 0xdd, 0xdf, 0x2d, 0xd8, 0x5d, 0x35, 0x46, 0x9b, 0xce, 0xbc, 0x02, 0x98, 0x30, 0xcd,
	0xc7, 0xa2, 0x08, 0x79, 0x56, 0xa7, 0xda, 0x6b, 0x1e, 0xf7, 0xfb, 0x37, 0x0c, 0xd0, 0xdf, 0x16,
	0xad, 0xa7, 0x5f, 0x25, 0xa9, 0xba, 0xa4, 0x8d, 0xc9, 0x6a, 0x7e, 0xf0, 0xf3, 0x46, 0x02, 0x04,
	0xc9, 0x1e, 0x54, 0xcf, 0xf8, 0xa5, 0xe9, 0x3d, 0x2d, 0x86, 0xe4, 0x19, 0xd8, 0x17, 0xd8, 0x8d,
	0xa2, 0xe3, 0xcd, 0xe3, 0xc3, 0x7b, 0xb3, 0x61, 0x32, 0x6a, 0xc8, 0x5f, 0x54, 0x3e, 0xb7, 0xba,
	0xff, 0xd6, 0xa0, 0x75, 0xaa, 0xe4, 0x54, 0xcc, 0xf9, 0xff, 0xd8, 0x57, 0xcf, 0x60, 0xe7, 0x6b,
	0x19, 0xb1, 0xb5, 0xda, 0xc6, 0xfd, 0xb7, 0xf2, 0xcc, 0x77, 0xe7, 0x25, 0x30, 0xaa, 0xd0, 0x6d,
	0x12, 0x79, 0x09, 0x4f, 0x56, 0x81, 0xd7, 0xa9, 0x12, 0xc9, 0xcc, 0x68, 0x1d, 0xcc, 0xfc, 0x24,
	0xcf, 0xfc, 0xf6, 0x4a, 0x3b, 0xd6, 0x88, 0x8f, 0xaa, 0xf4, 0x2e, 0xc5, 0x86, 0xad, 0xeb, 0x8f,
	0xb0, 0xb5, 0xfb, 0x38, 0x5b, 0x37, 0x1e, 0x69, 0x6b, 0x78, 0xd0, 0xd6, 0xcd, 0x7b, 0x6c, 0x4d,
	0x9e, 0x43, 0xed, 0x75, 0xca, 0x52, 0xaf, 0x85, 0xae, 0xe9, 0xdc, 0x72, 0xcd, 0xc0, 0xfc, 0x16,
	0x9c, 0xc2, 0x3c, 0x81, 0x9b, 0x67, 0x7e, 0x4d, 0xa7, 0x2c, 0xa5, 0xa8, 0xbb, 0xff, 0x5a, 0x04,
	0x00, 0xee, 0xaa, 0x50, 0xc1, 0x1e, 0xec, 0x6e, 0x17, 0xad, 0xfb, 0x57, 0x05, 0xda, 0x37, 0xd6,
	0x26, 0x1f, 0x43, 0xe3, 0x44, 0xce, 0xe7, 0xf2, 0xad, 0x48, 0x66, 0x68, 0x3f, 0xdb, 0x9c, 0x7d,
	0xba, 0x0a, 0xd2, 0x35, 0x4e, 0x9e, 0x42, 0xed, 0x84, 0x25, 0x1a, 0x8d, 0x68, 0x9b, 0x6d, 0x4d,
	0x59, 0xa2, 0x29, 0x46, 0x89, 0x0f, 0x76, 0x30, 0x67, 0xd1, 0x59, 0xe9, 0xbc, 0x46, 0x9e, 0xf9,
	0xf6, 0xa4, 0x08, 0x50, 0x13, 0x27, 0x47, 0x00, 0xdf, 0xcb, 0x85, 0x88, 0x5e, 0x14, 0x3b, 0x40,
	0xa7, 0xd9, 0x41, 0x3b, 0xcf, 0xfc, 0x66, 0x5a, 0x44, 0xc7, 0xb8, 0x31, 0xba, 0x41, 0x21, 0x9f,
	0x41, 0x6b, 0xa0, 0x52, 0x11, 0xcd, 0xb9, 0x91, 0xd8, 0x28, 0xd9, 0xcf, 0x33, 0x7f, 0x87, 0x99,
	0x78, 0x29, 0xda, 0xa2, 0x91, 0xe7, 0xd0, 0x1e, 0x0a, 0x1d, 0x2d, 0xb5, 0x16, 0x32, 0x31, 0x4a,
	0x07, 0x95, 0xef, 0xe6, 0x99, 0xbf, 0x17, 0x5f, 0x43, 0xa5, 0xf8, 0x26, 0x99, 0x1c, 0x43, 0x33,
	0xd4, 0xeb, 0xaa, 0x98, 0x87, 0xce, 0x5c, 0x09, 0x3d, 0x5e, 0x17, 0x66, 0x93, 0xd4, 0x7d, 0x05,
	0xce, 0x40, 0xc4, 0x94, 0xff, 0x4a, 0x3e, 0x80, 0x2a, 0x13, 0x71, 0x79, 0x95, 0xeb, 0x79, 0xe6,
	0x17, 0x53, 0x5a, 0x7c, 0x48, 0x0f, 0x5c, 0xc5, 0xcf, 0x65, 0xca, 0xc3, 0xd3, 0xf2, 0x32, 0xe3,
	0x55, 0x59, 0xc5, 0xe8, 0xf5, 0xa8, 0xfb, 0x1d, 0xd4, 0x07, 0x22, 0xd6, 0xc5, 0x7a, 0x4f, 0xa1,
	0xc6, 0x44, 0x6c, 0x5e, 0xb4, 0xaa, 0x29, 0x7a, 0x31, 0xa7, 0xf8, 0x7d, 0xfc, 0x92, 0xc7, 0xff,
	0x58, 0x50, 0x2f, 0xbb, 0x4f, 0x86, 0xd0, 0x08, 0x98, 0x16, 0x11, 0x5a, 0xe0, 0xfd, 0xdb, 0x06,
	0xc4, 0x93, 0x1c, 0x3c, 0xf0, 0x9e, 0x91, 0x11, 0x34, 0x37, 0xec, 0x74, 0xff, 0x3a, 0x0f, 0x3a,
	0x9c, 0x9c, 0xe0, 0x7e, 0xcc, 0x63, 0x4b, 0xbc, 0xbb, 0xd6, 0x29, 0x4a, 0x71, 0xe0, 0x3f, 0xf0,
	0x9c, 0x07, 0xfb, 0x7f, 0x5c, 0x1d, 0x5a, 0x7f, 0x5e, 0x1d, 0x5a, 0x7f, 0x5f, 0x1d, 0x5a, 0x3f,
	0x55, 0xd9, 0x42, 0x4c, 0x1c, 0xfc, 0x27, 0xff, 0xf4, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x46,
	0xbe, 0xa5, 0xc7, 0x15, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	BasicInfo(ctx context.Context, in *AidReq, opts ...grpc.CallOption) (*BaseInfoReply, error)
	AccountStat(ctx context.Context, in *AidReq, opts ...grpc.CallOption) (*AccountStatInfo, error)
	BaseInfos(ctx context.Context, in *AidsReq, opts ...grpc.CallOption) (*BaseInfosReply, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) BasicInfo(ctx context.Context, in *AidReq, opts ...grpc.CallOption) (*BaseInfoReply, error) {
	out := new(BaseInfoReply)
	err := c.cc.Invoke(ctx, "/service.account.Account/BasicInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) AccountStat(ctx context.Context, in *AidReq, opts ...grpc.CallOption) (*AccountStatInfo, error) {
	out := new(AccountStatInfo)
	err := c.cc.Invoke(ctx, "/service.account.Account/AccountStat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) BaseInfos(ctx context.Context, in *AidsReq, opts ...grpc.CallOption) (*BaseInfosReply, error) {
	out := new(BaseInfosReply)
	err := c.cc.Invoke(ctx, "/service.account.Account/BaseInfos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	BasicInfo(context.Context, *AidReq) (*BaseInfoReply, error)
	AccountStat(context.Context, *AidReq) (*AccountStatInfo, error)
	BaseInfos(context.Context, *AidsReq) (*BaseInfosReply, error)
}

// UnimplementedAccountServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServer struct {
}

func (*UnimplementedAccountServer) BasicInfo(ctx context.Context, req *AidReq) (*BaseInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BasicInfo not implemented")
}
func (*UnimplementedAccountServer) AccountStat(ctx context.Context, req *AidReq) (*AccountStatInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountStat not implemented")
}
func (*UnimplementedAccountServer) BaseInfos(ctx context.Context, req *AidsReq) (*BaseInfosReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaseInfos not implemented")
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_BasicInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).BasicInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.account.Account/BasicInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).BasicInfo(ctx, req.(*AidReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_AccountStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).AccountStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.account.Account/AccountStat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).AccountStat(ctx, req.(*AidReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_BaseInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AidsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).BaseInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.account.Account/BaseInfos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).BaseInfos(ctx, req.(*AidsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.account.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BasicInfo",
			Handler:    _Account_BasicInfo_Handler,
		},
		{
			MethodName: "AccountStat",
			Handler:    _Account_AccountStat_Handler,
		},
		{
			MethodName: "BaseInfos",
			Handler:    _Account_BaseInfos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb.proto",
}

func (m *BaseInfoReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BaseInfoReply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BaseInfoReply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.IsVIP {
		i--
		if m.IsVIP {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if m.IsOrg {
		i--
		if m.IsOrg {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.WorkCert {
		i--
		if m.WorkCert {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.IDCert {
		i--
		if m.IDCert {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if len(m.Avatar) > 0 {
		i -= len(m.Avatar)
		copy(dAtA[i:], m.Avatar)
		i = encodeVarintPb(dAtA, i, uint64(len(m.Avatar)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Introduction != nil {
		{
			size := m.Introduction.Size()
			i -= size
			if _, err := m.Introduction.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.Gender != nil {
		{
			size := m.Gender.Size()
			i -= size
			if _, err := m.Gender.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if len(m.UserName) > 0 {
		i -= len(m.UserName)
		copy(dAtA[i:], m.UserName)
		i = encodeVarintPb(dAtA, i, uint64(len(m.UserName)))
		i--
		dAtA[i] = 0x12
	}
	if m.ID != 0 {
		i = encodeVarintPb(dAtA, i, uint64(m.ID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BaseInfoReply_GenderValue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BaseInfoReply_GenderValue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintPb(dAtA, i, uint64(m.GenderValue))
	i--
	dAtA[i] = 0x18
	return len(dAtA) - i, nil
}
func (m *BaseInfoReply_IntroductionValue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BaseInfoReply_IntroductionValue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= len(m.IntroductionValue)
	copy(dAtA[i:], m.IntroductionValue)
	i = encodeVarintPb(dAtA, i, uint64(len(m.IntroductionValue)))
	i--
	dAtA[i] = 0x22
	return len(dAtA) - i, nil
}
func (m *BaseInfosReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BaseInfosReply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BaseInfosReply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.BaseInfos) > 0 {
		for k := range m.BaseInfos {
			v := m.BaseInfos[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintPb(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i = encodeVarintPb(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintPb(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ProfileReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProfileReply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProfileReply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Stat != nil {
		{
			size, err := m.Stat.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPb(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x62
	}
	if m.IsVIP {
		i--
		if m.IsVIP {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if m.IsOrg {
		i--
		if m.IsOrg {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if m.WorkCert {
		i--
		if m.WorkCert {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if m.IDCert {
		i--
		if m.IDCert {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if len(m.Avatar) > 0 {
		i -= len(m.Avatar)
		copy(dAtA[i:], m.Avatar)
		i = encodeVarintPb(dAtA, i, uint64(len(m.Avatar)))
		i--
		dAtA[i] = 0x3a
	}
	if m.LocationString != nil {
		{
			size := m.LocationString.Size()
			i -= size
			if _, err := m.LocationString.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.Location != nil {
		{
			size := m.Location.Size()
			i -= size
			if _, err := m.Location.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.Introduction != nil {
		{
			size := m.Introduction.Size()
			i -= size
			if _, err := m.Introduction.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.Gender != nil {
		{
			size := m.Gender.Size()
			i -= size
			if _, err := m.Gender.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if len(m.UserName) > 0 {
		i -= len(m.UserName)
		copy(dAtA[i:], m.UserName)
		i = encodeVarintPb(dAtA, i, uint64(len(m.UserName)))
		i--
		dAtA[i] = 0x12
	}
	if m.ID != 0 {
		i = encodeVarintPb(dAtA, i, uint64(m.ID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ProfileReply_GenderValue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProfileReply_GenderValue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintPb(dAtA, i, uint64(m.GenderValue))
	i--
	dAtA[i] = 0x18
	return len(dAtA) - i, nil
}
func (m *ProfileReply_IntroductionValue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProfileReply_IntroductionValue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= len(m.IntroductionValue)
	copy(dAtA[i:], m.IntroductionValue)
	i = encodeVarintPb(dAtA, i, uint64(len(m.IntroductionValue)))
	i--
	dAtA[i] = 0x22
	return len(dAtA) - i, nil
}
func (m *ProfileReply_LocationValue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProfileReply_LocationValue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintPb(dAtA, i, uint64(m.LocationValue))
	i--
	dAtA[i] = 0x28
	return len(dAtA) - i, nil
}
func (m *ProfileReply_LocationStringValue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProfileReply_LocationStringValue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= len(m.LocationStringValue)
	copy(dAtA[i:], m.LocationStringValue)
	i = encodeVarintPb(dAtA, i, uint64(len(m.LocationStringValue)))
	i--
	dAtA[i] = 0x32
	return len(dAtA) - i, nil
}
func (m *AccountStatInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountStatInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccountStatInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.IsFollowing {
		i--
		if m.IsFollowing {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.DiscussionCount != 0 {
		i = encodeVarintPb(dAtA, i, uint64(m.DiscussionCount))
		i--
		dAtA[i] = 0x30
	}
	if m.ArticleCount != 0 {
		i = encodeVarintPb(dAtA, i, uint64(m.ArticleCount))
		i--
		dAtA[i] = 0x28
	}
	if m.TopicCount != 0 {
		i = encodeVarintPb(dAtA, i, uint64(m.TopicCount))
		i--
		dAtA[i] = 0x20
	}
	if m.Black != 0 {
		i = encodeVarintPb(dAtA, i, uint64(m.Black))
		i--
		dAtA[i] = 0x18
	}
	if m.Fans != 0 {
		i = encodeVarintPb(dAtA, i, uint64(m.Fans))
		i--
		dAtA[i] = 0x10
	}
	if m.Following != 0 {
		i = encodeVarintPb(dAtA, i, uint64(m.Following))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AidReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AidReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AidReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.RemoteIP) > 0 {
		i -= len(m.RemoteIP)
		copy(dAtA[i:], m.RemoteIP)
		i = encodeVarintPb(dAtA, i, uint64(len(m.RemoteIP)))
		i--
		dAtA[i] = 0x12
	}
	if m.Aid != 0 {
		i = encodeVarintPb(dAtA, i, uint64(m.Aid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AidsReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AidsReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AidsReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.RemoteIP) > 0 {
		i -= len(m.RemoteIP)
		copy(dAtA[i:], m.RemoteIP)
		i = encodeVarintPb(dAtA, i, uint64(len(m.RemoteIP)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Aids) > 0 {
		dAtA4 := make([]byte, len(m.Aids)*10)
		var j3 int
		for _, num1 := range m.Aids {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintPb(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPb(dAtA []byte, offset int, v uint64) int {
	offset -= sovPb(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BaseInfoReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovPb(uint64(m.ID))
	}
	l = len(m.UserName)
	if l > 0 {
		n += 1 + l + sovPb(uint64(l))
	}
	if m.Gender != nil {
		n += m.Gender.Size()
	}
	if m.Introduction != nil {
		n += m.Introduction.Size()
	}
	l = len(m.Avatar)
	if l > 0 {
		n += 1 + l + sovPb(uint64(l))
	}
	if m.IDCert {
		n += 2
	}
	if m.WorkCert {
		n += 2
	}
	if m.IsOrg {
		n += 2
	}
	if m.IsVIP {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *BaseInfoReply_GenderValue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovPb(uint64(m.GenderValue))
	return n
}
func (m *BaseInfoReply_IntroductionValue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.IntroductionValue)
	n += 1 + l + sovPb(uint64(l))
	return n
}
func (m *BaseInfosReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.BaseInfos) > 0 {
		for k, v := range m.BaseInfos {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovPb(uint64(l))
			}
			mapEntrySize := 1 + sovPb(uint64(k)) + l
			n += mapEntrySize + 1 + sovPb(uint64(mapEntrySize))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ProfileReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovPb(uint64(m.ID))
	}
	l = len(m.UserName)
	if l > 0 {
		n += 1 + l + sovPb(uint64(l))
	}
	if m.Gender != nil {
		n += m.Gender.Size()
	}
	if m.Introduction != nil {
		n += m.Introduction.Size()
	}
	if m.Location != nil {
		n += m.Location.Size()
	}
	if m.LocationString != nil {
		n += m.LocationString.Size()
	}
	l = len(m.Avatar)
	if l > 0 {
		n += 1 + l + sovPb(uint64(l))
	}
	if m.IDCert {
		n += 2
	}
	if m.WorkCert {
		n += 2
	}
	if m.IsOrg {
		n += 2
	}
	if m.IsVIP {
		n += 2
	}
	if m.Stat != nil {
		l = m.Stat.Size()
		n += 1 + l + sovPb(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ProfileReply_GenderValue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovPb(uint64(m.GenderValue))
	return n
}
func (m *ProfileReply_IntroductionValue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.IntroductionValue)
	n += 1 + l + sovPb(uint64(l))
	return n
}
func (m *ProfileReply_LocationValue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovPb(uint64(m.LocationValue))
	return n
}
func (m *ProfileReply_LocationStringValue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.LocationStringValue)
	n += 1 + l + sovPb(uint64(l))
	return n
}
func (m *AccountStatInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Following != 0 {
		n += 1 + sovPb(uint64(m.Following))
	}
	if m.Fans != 0 {
		n += 1 + sovPb(uint64(m.Fans))
	}
	if m.Black != 0 {
		n += 1 + sovPb(uint64(m.Black))
	}
	if m.TopicCount != 0 {
		n += 1 + sovPb(uint64(m.TopicCount))
	}
	if m.ArticleCount != 0 {
		n += 1 + sovPb(uint64(m.ArticleCount))
	}
	if m.DiscussionCount != 0 {
		n += 1 + sovPb(uint64(m.DiscussionCount))
	}
	if m.IsFollowing {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *AidReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Aid != 0 {
		n += 1 + sovPb(uint64(m.Aid))
	}
	l = len(m.RemoteIP)
	if l > 0 {
		n += 1 + l + sovPb(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *AidsReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Aids) > 0 {
		l = 0
		for _, e := range m.Aids {
			l += sovPb(uint64(e))
		}
		n += 1 + sovPb(uint64(l)) + l
	}
	l = len(m.RemoteIP)
	if l > 0 {
		n += 1 + l + sovPb(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovPb(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPb(x uint64) (n int) {
	return sovPb(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BaseInfoReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BaseInfoReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BaseInfoReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenderValue", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Gender = &BaseInfoReply_GenderValue{v}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IntroductionValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Introduction = &BaseInfoReply_IntroductionValue{string(dAtA[iNdEx:postIndex])}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Avatar", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Avatar = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IDCert", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IDCert = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkCert", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WorkCert = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsOrg", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsOrg = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsVIP", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsVIP = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipPb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BaseInfosReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BaseInfosReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BaseInfosReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseInfos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BaseInfos == nil {
				m.BaseInfos = make(map[int64]*BaseInfoReply)
			}
			var mapkey int64
			var mapvalue *BaseInfoReply
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPb
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPb
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPb
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthPb
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthPb
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &BaseInfoReply{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipPb(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthPb
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.BaseInfos[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProfileReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProfileReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProfileReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenderValue", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Gender = &ProfileReply_GenderValue{v}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IntroductionValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Introduction = &ProfileReply_IntroductionValue{string(dAtA[iNdEx:postIndex])}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LocationValue", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Location = &ProfileReply_LocationValue{v}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LocationStringValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LocationString = &ProfileReply_LocationStringValue{string(dAtA[iNdEx:postIndex])}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Avatar", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Avatar = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IDCert", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IDCert = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkCert", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WorkCert = bool(v != 0)
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsOrg", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsOrg = bool(v != 0)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsVIP", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsVIP = bool(v != 0)
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stat", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Stat == nil {
				m.Stat = &AccountStatInfo{}
			}
			if err := m.Stat.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountStatInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountStatInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountStatInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Following", wireType)
			}
			m.Following = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Following |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fans", wireType)
			}
			m.Fans = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Fans |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Black", wireType)
			}
			m.Black = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Black |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TopicCount", wireType)
			}
			m.TopicCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TopicCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArticleCount", wireType)
			}
			m.ArticleCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ArticleCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DiscussionCount", wireType)
			}
			m.DiscussionCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DiscussionCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsFollowing", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsFollowing = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipPb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AidReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AidReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AidReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Aid", wireType)
			}
			m.Aid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Aid |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoteIP", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemoteIP = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AidsReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AidsReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AidsReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPb
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Aids = append(m.Aids, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPb
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthPb
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthPb
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Aids) == 0 {
					m.Aids = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPb
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Aids = append(m.Aids, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Aids", wireType)
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoteIP", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemoteIP = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPb(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPb
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPb
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthPb
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowPb
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipPb(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthPb
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthPb = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPb   = fmt.Errorf("proto: integer overflow")
)
