version: '3'

services:
    redis:
      image: redis
      hostname: redis
      environment:
        - REGION=hz
        - ZONE=hz001
        - DEPLOY_ENV=dev
      networks:
        - flywk
      ports:
        - "6379:6379"
      restart: on-failure
    memcached:
      image: memcached
      hostname: memcached
      environment:
        - REGION=hz
        - ZONE=hz001
        - DEPLOY_ENV=dev
      networks:
        - flywk
      ports:
        - "11211:11211"
      restart: on-failure
    mysql:
      image: mysql/mysql-server
      hostname: mysql
      environment:
        - REGION=hz
        - ZONE=hz001
        - DEPLOY_ENV=dev
        - MYSQL_ROOT_PASSWORD=123456
      networks:
        - flywk
      ports:
        - "3306:3306"
      volumes:
        - /Users/jack/projects/docker/mysql:/var/lib/mysql
      restart: on-failure
networks:
  flywk:
    # Use a custom driver
    driver: bridge