package repo

import "github.com/gobuffalo/packr"

// !!! GENERATED FILE !!!
// Do NOT hand edit this file!!
// It is recommended that you DO NOT check into this file into SCM.
// We STRONGLY recommend you delete this file after you have built your
// Go binary. You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("./sql/session", "DELETE.sql", "\"VVBEQVRFIHNlc3Npb24KU0VUIGRlbGV0ZWQ9MQpXSEVSRSBpZD06aWQK\"")
	packr.PackJSONBytes("./sql/session", "GET_ALL.sql", "\"U0VMRUNUIGEuKgpGUk9NIHNlc3Npb24gYQpXSEVSRSBhLmRlbGV0ZWQ9MApPUkRFUiBCWSBhLmlkIERFU0MK\"")
	packr.PackJSONBytes("./sql/session", "GET_ALL_BY_CONDITION.sql", "\"U0VMRUNUIGEuKgpGUk9NIHNlc3Npb24gYQpXSEVSRSBhLmRlbGV0ZWQ9MCAlcwpPUkRFUiBCWSBhLmlkIERFU0MK\"")
	packr.PackJSONBytes("./sql/session", "GET_BY_CONDITION.sql", "\"U0VMRUNUCmEuKgpGUk9NIHNlc3Npb24gYQpXSEVSRSBhLmRlbGV0ZWQ9MCAlcw==\"")
	packr.PackJSONBytes("./sql/session", "GET_BY_ID.sql", "\"U0VMRUNUCiAgICBhLmlkLAogICAgYS5zZXNzaW9uX3R5cGUsCiAgICBhLnVzZWQsCiAgICBhLmFjY291bnRfaWQsCiAgICBhLmRlbGV0ZWQsCiAgICBhLmNyZWF0ZWRfYXQsCiAgICBhLnVwZGF0ZWRfYXQKRlJPTSBzZXNzaW9uIGEKV0hFUkUgYS5pZD06aWQgQU5EIGEuZGVsZXRlZD0w\"")
	packr.PackJSONBytes("./sql/session", "INSERT.sql", "\"SU5TRVJUIElOVE8gc2Vzc2lvbigKICAgIGlkLAogICAgc2Vzc2lvbl90eXBlLAogICAgdXNlZCwKICAgIGFjY291bnRfaWQsCiAgICBkZWxldGVkLAogICAgY3JlYXRlZF9hdCwKICAgIHVwZGF0ZWRfYXQKKSBWQUxVRVMgKAogICAgOmlkLAogICAgOnNlc3Npb25fdHlwZSwKICAgIDp1c2VkLAogICAgOmFjY291bnRfaWQsCiAgICA6ZGVsZXRlZCwKICAgIDpjcmVhdGVkX2F0LAogICAgOnVwZGF0ZWRfYXQKKQ==\"")
	packr.PackJSONBytes("./sql/session", "QUERY_LIST_PAGED_COUNT.sql", "\"U0VMRUNUIENPVU5UKDEpIGFzIGNvdW50CkZST00gc2Vzc2lvbiBhCldIRVJFIGEuZGVsZXRlZD0wICVz\"")
	packr.PackJSONBytes("./sql/session", "QUERY_LIST_PAGED_DATA.sql", "\"U0VMRUNUIGEuKgpGUk9NIHNlc3Npb24gYQpXSEVSRSBhLmRlbGV0ZWQ9MCAlcwpPUkRFUiBCWSBhLmlkIERFU0MgTElNSVQgOmxpbWl0IE9GRlNFVCA6b2Zmc2V0Cg==\"")
	packr.PackJSONBytes("./sql/session", "UPDATE.sql", "\"VVBEQVRFIHNlc3Npb24KU0VUCiAgICBzZXNzaW9uX3R5cGU9OnNlc3Npb25fdHlwZSwKICAgIHVzZWQ9OnVzZWQsCiAgICBhY2NvdW50X2lkPTphY2NvdW50X2lkLAogICAgdXBkYXRlZF9hdD06dXBkYXRlZF9hdApXSEVSRSBpZD06aWQK\"")
	packr.PackJSONBytes("./sql/valcode", "DELETE.sql", "\"VVBEQVRFIHZhbGNvZGVzClNFVCBkZWxldGVkPTEKV0hFUkUgaWQ9OmlkCg==\"")
	packr.PackJSONBytes("./sql/valcode", "GET_ALL.sql", "\"U0VMRUNUIGEuKgpGUk9NIHZhbGNvZGVzIGEKV0hFUkUgYS5kZWxldGVkPTAKT1JERVIgQlkgYS5pZCBERVNDCg==\"")
	packr.PackJSONBytes("./sql/valcode", "GET_ALL_BY_CONDITION.sql", "\"U0VMRUNUIGEuKgpGUk9NIHZhbGNvZGVzIGEKV0hFUkUgYS5kZWxldGVkPTAgJXMKT1JERVIgQlkgYS5pZCBERVNDCg==\"")
	packr.PackJSONBytes("./sql/valcode", "GET_BY_CONDITION.sql", "\"U0VMRUNUCmEuKgpGUk9NIHZhbGNvZGVzIGEKV0hFUkUgYS5kZWxldGVkPTAgJXM=\"")
	packr.PackJSONBytes("./sql/valcode", "GET_BY_ID.sql", "\"U0VMRUNUCiAgICBhLmlkLAogICAgYS5jb2RlX3R5cGUsCiAgICBhLnVzZWQsCiAgICBhLmNvZGUsCiAgICBhLmlkZW50aXR5LAogICAgYS5kZWxldGVkLAogICAgYS5jcmVhdGVkX2F0LAogICAgYS51cGRhdGVkX2F0CkZST00gdmFsY29kZXMgYQpXSEVSRSBhLmlkPTppZCBBTkQgYS5kZWxldGVkPTA=\"")
	packr.PackJSONBytes("./sql/valcode", "INSERT.sql", "\"SU5TRVJUIElOVE8gdmFsY29kZXMoCiAgICBpZCwKICAgIGNvZGVfdHlwZSwKICAgIHVzZWQsCiAgICBjb2RlLAogICAgaWRlbnRpdHksCiAgICBkZWxldGVkLAogICAgY3JlYXRlZF9hdCwKICAgIHVwZGF0ZWRfYXQKKSBWQUxVRVMgKAogICAgOmlkLAogICAgOmNvZGVfdHlwZSwKICAgIDp1c2VkLAogICAgOmNvZGUsCiAgICA6aWRlbnRpdHksCiAgICA6ZGVsZXRlZCwKICAgIDpjcmVhdGVkX2F0LAogICAgOnVwZGF0ZWRfYXQKKQ==\"")
	packr.PackJSONBytes("./sql/valcode", "QUERY_LIST_PAGED_COUNT.sql", "\"U0VMRUNUIENPVU5UKDEpIGFzIGNvdW50CkZST00gdmFsY29kZXMgYQpXSEVSRSBhLmRlbGV0ZWQ9MCAlcw==\"")
	packr.PackJSONBytes("./sql/valcode", "QUERY_LIST_PAGED_DATA.sql", "\"U0VMRUNUIGEuKgpGUk9NIHZhbGNvZGVzIGEKV0hFUkUgYS5kZWxldGVkPTAgJXMKT1JERVIgQlkgYS5pZCBERVNDIExJTUlUIDpsaW1pdCBPRkZTRVQgOm9mZnNldAo=\"")
	packr.PackJSONBytes("./sql/valcode", "UPDATE.sql", "\"VVBEQVRFIHZhbGNvZGVzClNFVAogICAgY29kZV90eXBlPTpjb2RlX3R5cGUsCiAgICB1c2VkPTp1c2VkLAogICAgY29kZT06Y29kZSwKICAgIGlkZW50aXR5PTppZGVudGl0eSwKICAgIHVwZGF0ZWRfYXQ9OnVwZGF0ZWRfYXQKV0hFUkUgaWQ9OmlkCg==\"")
	packr.PackJSONBytes("./sql/account", "DELETE.sql", "\"VVBEQVRFIGFjY291bnRzClNFVCBkZWxldGVkPTEKV0hFUkUgaWQ9OmlkCg==\"")
	packr.PackJSONBytes("./sql/account", "GET_ALL.sql", "\"U0VMRUNUIGEuKgpGUk9NIGFjY291bnRzIGEKV0hFUkUgYS5kZWxldGVkPTAKT1JERVIgQlkgYS5pZCBERVNDCg==\"")
	packr.PackJSONBytes("./sql/account", "GET_ALL_BY_CONDITION.sql", "\"U0VMRUNUIGEuKgpGUk9NIGFjY291bnRzIGEKV0hFUkUgYS5kZWxldGVkPTAgJXMKT1JERVIgQlkgYS5pZCBERVNDCg==\"")
	packr.PackJSONBytes("./sql/account", "GET_BY_CONDITION.sql", "\"U0VMRUNUCmEuKgpGUk9NIGFjY291bnRzIGEKV0hFUkUgYS5kZWxldGVkPTAgJXM=\"")
	packr.PackJSONBytes("./sql/account", "GET_BY_ID.sql", "\"U0VMRUNUCiAgICBhLmlkLAogICAgYS5tb2JpbGUsCiAgICBhLmVtYWlsLAogICAgYS5wYXNzd29yZCwKICAgIGEuZ2VuZGVyLAogICAgYS5iaXJ0aF95ZWFyLAogICAgYS5iaXJ0aF9tb250aCwKICAgIGEuYmlydGhfZGF5LAogICAgYS5pbnRyb2R1Y3Rpb24sCiAgICBhLmF2YXRhciwKICAgIGEuc291cmNlLAogICAgYS5pcCwKICAgIGEuZGVsZXRlZCwKICAgIGEuY3JlYXRlZF9hdCwKICAgIGEudXBkYXRlZF9hdApGUk9NIGFjY291bnRzIGEKV0hFUkUgYS5pZD06aWQgQU5EIGEuZGVsZXRlZD0w\"")
	packr.PackJSONBytes("./sql/account", "INSERT.sql", "\"SU5TRVJUIElOVE8gYWNjb3VudHMoCiAgICBpZCwKICAgIG1vYmlsZSwKICAgIGVtYWlsLAogICAgcGFzc3dvcmQsCiAgICBnZW5kZXIsCiAgICBiaXJ0aF95ZWFyLAogICAgYmlydGhfbW9udGgsCiAgICBiaXJ0aF9kYXksCiAgICBpbnRyb2R1Y3Rpb24sCiAgICBhdmF0YXIsCiAgICBzb3VyY2UsCiAgICBpcCwKICAgIGRlbGV0ZWQsCiAgICBjcmVhdGVkX2F0LAogICAgdXBkYXRlZF9hdAopIFZBTFVFUyAoCiAgICA6aWQsCiAgICA6bW9iaWxlLAogICAgOmVtYWlsLAogICAgOnBhc3N3b3JkLAogICAgOmdlbmRlciwKICAgIDpiaXJ0aF95ZWFyLAogICAgOmJpcnRoX21vbnRoLAogICAgOmJpcnRoX2RheSwKICAgIDppbnRyb2R1Y3Rpb24sCiAgICA6YXZhdGFyLAogICAgOnNvdXJjZSwKICAgIDppcCwKICAgIDpkZWxldGVkLAogICAgOmNyZWF0ZWRfYXQsCiAgICA6dXBkYXRlZF9hdAop\"")
	packr.PackJSONBytes("./sql/account", "QUERY_LIST_PAGED_COUNT.sql", "\"U0VMRUNUIENPVU5UKDEpIGFzIGNvdW50CkZST00gYWNjb3VudHMgYQpXSEVSRSBhLmRlbGV0ZWQ9MCAlcw==\"")
	packr.PackJSONBytes("./sql/account", "QUERY_LIST_PAGED_DATA.sql", "\"U0VMRUNUIGEuKgpGUk9NIGFjY291bnRzIGEKV0hFUkUgYS5kZWxldGVkPTAgJXMKT1JERVIgQlkgYS5pZCBERVNDIExJTUlUIDpsaW1pdCBPRkZTRVQgOm9mZnNldAo=\"")
	packr.PackJSONBytes("./sql/account", "UPDATE.sql", "\"VVBEQVRFIGFjY291bnRzClNFVAogICAgbW9iaWxlPTptb2JpbGUsCiAgICBlbWFpbD06ZW1haWwsCiAgICBwYXNzd29yZD06cGFzc3dvcmQsCiAgICBnZW5kZXI9OmdlbmRlciwKICAgIGJpcnRoX3llYXI9OmJpcnRoX3llYXIsCiAgICBiaXJ0aF9tb250aD06YmlydGhfbW9udGgsCiAgICBiaXJ0aF9kYXk9OmJpcnRoX2RheSwKICAgIGludHJvZHVjdGlvbj06aW50cm9kdWN0aW9uLAogICAgYXZhdGFyPTphdmF0YXIsCiAgICBzb3VyY2U9OnNvdXJjZSwKICAgIGlwPTppcCwKICAgIHVwZGF0ZWRfYXQ9OnVwZGF0ZWRfYXQKV0hFUkUgaWQ9OmlkCg==\"")
	}
