# This is a TOML document. Boom.

pollTimeout = "30s"
pathCache = "/tmp/"

[log]
stdout = true

[antispam]
    on=true
    second=60
    n=10
    hour=12
    m=500
    [antispam.redis]
        name = "config-service/hosts"
        proto = "tcp"
        addr = "redis-prod-master:6379"
        maxIdle = 100
        maxActive = 100
        dialTimeout = "1s"
        readTimeout = "1s"
        writeTimeout = "1s"
        idleTimeout = "10s"
        expire = "24h"

[ecode]
    domain = "ecode:6401"

[db]
    addr = "pc-bp15bm1vm861vj9xm.mysql.polardb.rds.aliyuncs.com:3306"
    dsn = "flywkacc:^EIj7UIjd@tcp(pc-bp15bm1vm861vj9xm.mysql.polardb.rds.aliyuncs.com:3306)/config_prod?parseTime=true&charset=utf8mb4"
    active = 5
    idle = 2
    queryTimeout = "1s"
    execTimeout = "2s"
    tranTimeout = "2s"
    [db.main.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
[redis]
    name = "config-service/hosts"
    proto = "tcp"
    addr = "redis-prod-master:6379"
    maxIdle = 100
    maxActive = 100
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"


[mars]
    address = "0.0.0.0:8000"
	maxListen = 10
    timeout="2s"


