# This is a TOML document. Boom.

pollTimeout = "30s"
pathCache = "/tmp/"

[log]
stdout = true

[antispam]
    on=true
    second=60
    n=10
    hour=12
    m=500
    [antispam.redis]
        name = "config-service/hosts"
        proto = "tcp"
        addr = "redis:6379"
        maxIdle = 100
        maxActive = 100
        dialTimeout = "1s"
        readTimeout = "1s"
        writeTimeout = "1s"
        idleTimeout = "10s"
        expire = "24h"

[ecode]
    domain = "ecode:6401"

[db]
    addr = "mysql:3306"
    dsn = "flywk:flywk@tcp(121.199.254.133:3306)/config_uat?parseTime=true&charset=utf8mb4 "
    active = 5
    idle = 2
    queryTimeout = "1s"
    execTimeout = "2s"
    tranTimeout = "2s"
    [db.main.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
[redis]
    name = "config-service/hosts"
    proto = "tcp"
    addr = "redis:6379"
    maxIdle = 100
    maxActive = 100
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"


[mars]
    address = "0.0.0.0:8001"
	maxListen = 10
    timeout="2s"

[discovery]
   nodes = ["192.168.0.136:7171"]
   key = "6a29f8ed87407c11"
   secret = "d3c5a85f5b895a03735b5d20a273bc57"
   env = "dev"
   zone = "hz001"
