[wardenServer]
    addr = "0.0.0.0:8099"
    timeout = "1s"

[db.auth]
    addr = "127.0.0.1:3306"
    dsn = "flywk:flywk@tcp(127.0.0.1:3306)/auth_dev?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4"
    active = 5
    idle = 2
    queryTimeout = "1s"
    execTimeout = "2s"
    tranTimeout = "2s"
    [db.auth.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
[db.main]
    addr = "127.0.0.1:3306"
    dsn = "flywk:flywk@tcp(127.0.0.1:3306)/flywk_dev?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4"
    active = 5
    idle = 2
    queryTimeout = "1s"
    execTimeout = "2s"
    tranTimeout = "2s"
    [db.main.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[authMC]
    expire = "24h"
	name = "valerian-main"
	proto = "tcp"
	addr = "127.0.0.1:11211"
	active = 50
	idle = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"

[mars]
    address = "0.0.0.0:8000"
    timeout = "1s"
