[ecode]
    domain = "localhost:6401"

[db.apm]
    addr = "mysql:3306"
    dsn = "flywk:flywk@tcp(121.199.254.133:3306)/apm_uat?parseTime=true&charset=utf8mb4 "
    active = 5
    idle = 2
    queryTimeout = "1s"
    execTimeout = "2s"
    tranTimeout = "2s"
    [db.apm.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100


[db.config]
    addr = "mysql:3306"
    dsn = "flywk:flywk@tcp(121.199.254.133:3306)/config_uat?parseTime=true&charset=utf8mb4 "
    active = 5
    idle = 2
    queryTimeout = "1s"
    execTimeout = "2s"
    tranTimeout = "2s"
    [db.config.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100


[mars]
    address = "0.0.0.0:8000"
    maxListen = 10
    timeout="2s"

[tree]
platform = "2F3b8fDVGlMnj8aCDlMaW"


[ConfSvr]
timeout = "1s"

