[httpClient]
    key = "654af11b5df0c9d3"
    secret = "a7512b8b243b82f4bdb72cf2824b3f8e"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"

[db.auth]
    addr = "127.0.0.1:3306"
    dsn = "flywk:flywk@tcp(mysql:3306)/auth_dev?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4"
    active = 5
    idle = 2
    queryTimeout = "1s"
    execTimeout = "2s"
    tranTimeout = "2s"
    [db.auth.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
[db.main]
    addr = "127.0.0.1:3306"
    dsn = "flywk:flywk@tcp(mysql:3306)/flywk_dev?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4"
    active = 5
    idle = 2
    queryTimeout = "1s"
    execTimeout = "2s"
    tranTimeout = "2s"
    [db.main.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
[db.apm]
    addr = "127.0.0.1:3306"
    dsn = "flywk:flywk@tcp(mysql:3306)/apm_dev?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4"
    active = 5
    idle = 2
    queryTimeout = "1s"
    execTimeout = "2s"
    tranTimeout = "2s"
    [db.apm.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
[tree]
    host = "http://easyst.fkywk.com"
    platformID = "flywk"
